### ISSUE TITLE
add the reference code 

### ISSUE THREAD

**Issue by purelyvivid** [anandpawara/Real_Time_Image_Animation#1]
since the main modules are almost the same with [https://github.com/AliaksandrSiarohin/first-order-model](https://github.com/AliaksandrSiarohin/first-order-model)
might consider to add the reference code in README.md?

**Comment by nile649** [comment]
I didn't see any reference paper...

**Comment by nile649** [comment]
@purelyvivid thanks for the link, because I was really confused with the results.

**Comment by anandpawara** [comment]
You can find links related to original project in CREDITS.md file, also might add to README.md
