### ISSUE TITLE
Output is really weird and unexpected 

### ISSUE THREAD

**Issue by Ftuuky** [anandpawara/Real_Time_Image_Animation#11]
Lovely project but when trying to run it the output was unexpected.

I got some user warnings but similar to the ones in the jupyter notebook shared in the repo.

All the outputs look like this:

![image](https://user-images.githubusercontent.com/16304630/83079092-f546df80-a072-11ea-88d3-dd9fb087d61a.png)

Any idea of what I did wrong?

**Comment by zcccccccccccc** [comment]
Congret, you just made another TO-BE-WORLD-FAMOUS painting

**Comment by anandpawara** [comment]
> Lovely project but when trying to run it the output was unexpected.
> 
> I got some user warnings but similar to the ones in the jupyter notebook shared in the repo.
> 
> All the outputs look like this:
> 
> ![image](https://user-images.githubusercontent.com/16304630/83079092-f546df80-a072-11ea-88d3-dd9fb087d61a.png)
> 
> Any idea of what I did wrong?

You did nothing wrong the output of the image depends on first frame frame opencv, If the user is not correctly oriented or not present, then the because of first frame , the application outputs bizzare results need to work on taking best frame of refrence before generating output

**Comment by Otter-man** [comment]
@anandpawara solution for this problem might be easier. 
Maybe add the "reset" button, that will make the reference frame the current one. So if the user is not correctly oriented or not present he can reset the reference frame on the fly. 

Will be like this:
User seeing distorted image will position himself correctly, will press there "reset button"  and the generation will restart using the ref.frame as the frame that was when the button was pressed.

This solution is used in other real-time deepfake generator project: https://github.com/alew3/faceit_live3

I'm trying to implement this myself but i'm not that familiar with opencv and can't figure how to recreate it in your code. Maybe you'll be able to implement it yourself faster.

**Comment by anandpawara** [comment]
> @anandpawara solution for this problem might be easier.
> Maybe add the "reset" button, that will make the reference frame the current one. So if the user is not correctly oriented or not present he can reset the reference frame on the fly.
> 
> Will be like this:
> User seeing distorted image will position himself correctly, will press there "reset button" and the generation will restart using current frame (at the time of the button push) as a ref.frame.
> 
> This solution is used in other real-time deepfake generator project: https://github.com/alew3/faceit_live3
> 
> I'm trying to implement this myself but i'm not that familiar with opencv and can't yet figure how to recreate it in your code. Maybe you'll be able to implement it yourself faster.

This is exactly I was planning to make in future , thanks for the lead may I'll try to integrate with current project

**Comment by Ftuuky** [comment]
Thanks everyone, I see what I need to do now! 

Will close this issue.
